apiVersion: v1
kind: PersistentVolume
metadata:
  name: nlp.solrserver.backup
  namespace: fabricnlp
  labels:
    type: local  
    namespace: fabricnlp
spec:
  #persistentVolumeReclaimPolicy: Delete
  storageClassName: default
  capacity:
    storage: 32Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/fabricnlp_backups"
  claimRef:
    namespace: fabricnlp
    name: nlp.solrserver.backup
