apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: nlpjobs-ingress-path
    namespace: fabricnlp
    labels:  
        expose: external    
    annotations:
        kubernetes.io/ingress.class: traefik
spec:
  rules:
  - http:
      paths:
      - path: /nlp
        backend:
          serviceName: nlpjobsserverpublic
          servicePort: 80
