kind: Service
apiVersion: v1
metadata:
  name: mysql-direct-port
  namespace: fabricnlp
  labels:
    dns: mysql    
spec:
  selector:
    app: mysqlserver
  ports:
  - name: mysqlport
    protocol: TCP
    port: 3306
    targetPort: 3306
  type: LoadBalancer  
---