kind: Deployment
apiVersion: extensions/v1beta1
metadata:
# name for this pod
  name: fabric.nlp.dnstester
# namespace for this pod
  namespace: fabricnlp
  labels:
    app: dnstester
spec:
  replicas: 1
  revisionHistoryLimit: 3  # Clean-up old Replica Sets deployed; only keep previous 3.
  strategy:
    # We need to kill the existing Pod before creating an new one
    # for the new one to be able to attach the persistent disk.
    type: Recreate
  selector:
    matchLabels:
      app: dnstester
  template:
    metadata:
      labels:
        app: dnstester
    spec:
      containers:
      - image: healthcatalyst/fabric.docker.dnstester:1
        imagePullPolicy: Always
        name: dnstester
        env:
          - name: ENVNAME
            value: {{ .Values.environmentName }}
          - name: SLACKURL
            value: {{ .Values.slackUrl }}
          - name: SLEEPINTERVAL
            value: {{ .Values.monitoringSleepInterval }}
          - name: INTERVALBETWEENMESSAGES
            value: {{ .Values.monitoringIntervalBetweenMessages }}
          - name: SERVER1
            value: mysqlserver
        resources:
          limits:
            memory: "64Mi"
            cpu: "250m"
